# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programmieren und Softwareentwicklung lernen mit C#, Git, GitHub, etc. auf LernMoment bei Jan Suchotzki
description: Programmieren lernen mit C#, Git, GitHub, etc. auf LernMoment
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lernmoment.de" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
